# This section is considered when running `cargo deny check advisories`
# More documentation for the advisories section can be found here:
# https://embarkstudios.github.io/cargo-deny/checks/advisories/cfg.html
[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
notice = "warn"

ignore = [
   # Potential segfault in the time crate
    "RUSTSEC-2020-0071",
    # Potential unaligned read on atty
    "RUSTSEC-2021-0145"
]

# This section is considered when running `cargo deny check licenses`
# More documentation for the licenses section can be found here:
# https://embarkstudios.github.io/cargo-deny/checks/licenses/cfg.html
[licenses]
unlicensed = "deny"
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "ISC",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "Zlib",
    "OpenSSL",
]
# List of explicitly disallowed licenses
# See https://spdx.org/licenses/ for list of possible licenses
# [possible values: any SPDX 3.11 short identifier (+ optional exception)].
deny = [
    #"Nokia",
]

copyleft = "deny"
allow-osi-fsf-free = "neither"
default = "deny"
confidence-threshold = 0.8

[[licenses.clarify]]
name = "ring"
# SPDX considers OpenSSL to encompass both the OpenSSL and SSLeay licenses
# https://spdx.org/licenses/OpenSSL.html
# ISC - Both BoringSSL and ring use this for their new files
# MIT - "Files in third_party/ have their own licenses, as described therein. The MIT
# license, for third_party/fiat, which, unlike other third_party directories, is
# compiled into non-test libraries, is included below."
# OpenSSL - Obviously
expression = "ISC AND MIT AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

# This section is considered when running `cargo deny check bans`.
# More documentation about the 'bans' section can be found here:
# https://embarkstudios.github.io/cargo-deny/checks/bans/cfg.html
[bans]
multiple-versions = "deny"
wildcards = "allow"
highlight = "all"

# For each duplicate dependency, indicate the name of the dependency which
# introduces it.
skip = [
# filetime & parking_lot_core
    { name = "windows_x86_64_msvc", version = "=0.36.1" },
    { name = "windows_x86_64_gnu", version = "=0.36.1" },
    { name = "windows_i686_msvc", version = "=0.36.1" },
    { name = "windows_i686_gnu", version = "=0.36.1" },
    { name = "windows_aarch64_msvc", version = "=0.36.1" },
    { name = "windows-sys", version = "=0.36.1" },
# core_affinity & atty
    { name = "winapi", version = "=0.2.8" },
# getrandom & others
    { name = "wasi", version = "=0.9.0+wasi-snapshot-preview1" },
    { name = "wasi", version = "=0.10.2+wasi-snapshot-preview1" },
# ring & flume
    { name = "spin", version = "=0.5.2" },
# memcached-rs
    { name = "semver", version = "=0.9.0" },
# rand
    { name = "rand_core", version = "=0.5.1" },
# rand
    { name = "rand_chacha", version = "=0.2.2" },
# http-types
    { name = "rand", version = "=0.7.3" },
# redis
    { name = "itoa", version = "=0.4.8" },
# vte
    { name = "arrayvec", version = "=0.5.2" },
# unix_socket
    { name = "cfg-if", version = "=0.1.10" },
# rand
    { name = "getrandom", version = "=0.1.16" },
# combine
    { name = "tokio-util", version = "=0.6.10" },
# libmount
    { name = "nix", version = "=0.14.1" },
# chrono
    { name = "time", version = "=0.1.43" },
]


# More documentation about the 'sources' section can be found here:
# https://embarkstudios.github.io/cargo-deny/checks/sources/cfg.html
[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
