name: rust-toolchain
inputs:
  toolchain:
    description: |
      Rust toolchain name.
      See https://rust-lang.github.io/rustup/concepts/toolchains.html#toolchain-specification
    required: false
  target:
    description: Target triple to install for this toolchain
    required: false
  components:
    description: Space-separated list of components to be additionally installed for a new toolchain
    required: false

runs:
  using: composite
  steps:
    - shell: bash
      env:
        INPUTS_COMPONENTS: ${{ inputs.components }}
        INPUTS_TARGET: ${{ inputs.target }}
        INPUTS_TOOLCHAIN: ${{ inputs.toolchain }}
      run: |
        set -x
        rustup override set "${INPUTS_TOOLCHAIN:-stable}"
        if [[ -n "${INPUTS_TARGET}" ]]; then
          rustup target add ${INPUTS_TARGET}
        fi
        if [[ -n "${INPUTS_COMPONENTS}" ]]; then
          rustup component add ${INPUTS_COMPONENTS}
        fi
        cargo --version
        rustc --version
