name: nvcc-toolchain
inputs:
  cuda-version:
    description: CUDA Toolkit version
    required: true

runs:
  using: composite
  steps:
    - if: runner.os == 'Linux'
      shell: bash
      env:
        INPUTS_NAME: ${{ inputs.name }}
      run: .github/actions/nvcc-toolchain/install-cuda.sh ${INPUTS_NAME}

    - if: runner.os == 'Windows'
      shell: powershell
      env:
        INPUTS_CUDA_VERSION: ${{ inputs.cuda-version }}
      run: .\.github\actions\nvcc-toolchain\install-cuda.ps1 -cudaVersion ${INPUTS_CUDA_VERSION}
