name: sccache
base: core22
adopt-info: sccache

summary: sccache is ccache with cloud storage
description: |
    sccache is a [ccache](https://ccache.dev/)-like compiler caching tool. It
    is used as a compiler wrapper and avoids compilation when possible, storing
    cached results either on [local disk](#local) or in one of [several cloud
    storage backends](#storage-options).

    sccache includes support for caching the compilation of C/C++ code,
    [Rust](docs/Rust.md), as well as NVIDIA's CUDA using
    [nvcc](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html).

    sccache also provides [icecream](https://github.com/icecc/icecream)-style
    distributed compilation (automatic packaging of local toolchains) for all
    supported compilers (including Rust). The distributed compilation system
    includes several security features that icecream lacks such as
    authentication, transport layer encryption, and sandboxed compiler
    execution on build servers. See [the distributed
    quickstart](docs/DistributedQuickstart.md) guide for more information.

grade: stable
confinement: classic

apps:
    sccache:
        command: bin/sccache

parts:
    sccache:
        plugin: rust
        source: .
        override-pull: |
          craftctl default
          craftctl set version=$( git -C ${CRAFT_PART_SRC} describe --tags )
        build-packages:
        - cargo
        - libssl-dev
        - make
        - pkg-config
        rust-features:
        - gcs
        - redis
        - s3
        build-attributes:
        - enable-patchelf
