name: Benchmarks

# spell-checker:ignore codspeed dtolnay Swatinem

on:
  pull_request:
  push:
    branches:
      - '*'

permissions:
  contents: read # to fetch code (actions/checkout)

# End the current execution if there is a new changeset in the PR.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  benchmarks:
    name: Run ${{ matrix.mode }} benchmarks (CodSpeed)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mode:
          - simulation
          - memory
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - uses: dtolnay/rust-toolchain@stable # zizmor: ignore[unpinned-uses]

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - name: Install cargo-codspeed
        shell: bash
        run: cargo install cargo-codspeed --locked

      - name: Build benchmarks
        shell: bash
        run: cargo codspeed build

      - name: Run benchmarks
        uses: CodSpeedHQ/action@a4a36bb07c0638b0b4ca52bf1f3dad1b4289e52f # v4.18.1
        env:
          CODSPEED_LOG: debug
        with:
          mode: ${{ matrix.mode }}
          run: cargo codspeed run > /dev/null
          token: ${{ secrets.CODSPEED_TOKEN }}
