name: Snap

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  Snap:
    runs-on: ubuntu-latest

    timeout-minutes: 45

    strategy:
      matrix:
        platform:
        - amd64
        - armhf
        - arm64
        # Broken dependencies: - ppc64el
        # https://github.com/mozilla/sccache/issues/1442
        # Broken environment: - s390x

    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # needed for version determination

    - name: Build and publish the snap
      uses: canonical/actions/build-snap@multiarch
      with:
        architecture: ${{ matrix.platform }}
        snapcraft-token: ${{ secrets.SNAPCRAFT_TOKEN }}
        publish: ${{ github.event_name == 'pull_request' && github.repository == github.event.pull_request.head.repo.full_name }}
        publish-channel: edge/pr${{ github.event.number }}
