name: Snap

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  Snap:
    runs-on: ubuntu-latest

    timeout-minutes: 45

    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # needed for version determination

    - name: Build the snap
      uses: canonical/actions/build-snap@release
      with:
        review-opts: --allow-classic
